//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/Utility/Inputs/WorldDebugControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Utility/Inputs/WorldDebugControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @WorldDebugControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @WorldDebugControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""WorldDebugControls"",
    ""maps"": [
        {
            ""name"": ""DebuggingActions"",
            ""id"": ""b6719192-cf5b-4165-a95d-a4da1639b39c"",
            ""actions"": [
                {
                    ""name"": ""HeightViewing"",
                    ""type"": ""Button"",
                    ""id"": ""311489b8-8b0a-43c2-beba-40670111f664"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlopeViewing"",
                    ""type"": ""Button"",
                    ""id"": ""96f1f6b4-12d7-4135-bc4f-de910bfe0fd2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoistureView"",
                    ""type"": ""Button"",
                    ""id"": ""45242d5a-0d0b-4778-8abf-a7f57a54518f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlowView"",
                    ""type"": ""Button"",
                    ""id"": ""c3b4709f-df7d-4936-a64e-22f9600e171c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BiomeView"",
                    ""type"": ""Button"",
                    ""id"": ""449f442f-a5e7-41d9-a5cd-eb057ad6e85b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Regenerate"",
                    ""type"": ""Button"",
                    ""id"": ""427e1611-3c38-41e3-a43e-d4f11ef452aa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d77a6fc-96e5-4c18-8c61-430c0cb422cb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeightViewing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3797386b-e50a-4196-8eff-4044f93efb02"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlopeViewing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb40333a-6070-4cfd-9178-bc535b9b09b8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoistureView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a66cb7e3-bc67-402d-b58b-fd3f2483cfb8"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlowView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be511873-1525-4a77-b227-8e46fe9936a3"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BiomeView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07d85161-5d6c-4411-8ef0-2a0adca8aec7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regenerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DebuggingActions
        m_DebuggingActions = asset.FindActionMap("DebuggingActions", throwIfNotFound: true);
        m_DebuggingActions_HeightViewing = m_DebuggingActions.FindAction("HeightViewing", throwIfNotFound: true);
        m_DebuggingActions_SlopeViewing = m_DebuggingActions.FindAction("SlopeViewing", throwIfNotFound: true);
        m_DebuggingActions_MoistureView = m_DebuggingActions.FindAction("MoistureView", throwIfNotFound: true);
        m_DebuggingActions_FlowView = m_DebuggingActions.FindAction("FlowView", throwIfNotFound: true);
        m_DebuggingActions_BiomeView = m_DebuggingActions.FindAction("BiomeView", throwIfNotFound: true);
        m_DebuggingActions_Regenerate = m_DebuggingActions.FindAction("Regenerate", throwIfNotFound: true);
    }

    ~@WorldDebugControls()
    {
        UnityEngine.Debug.Assert(!m_DebuggingActions.enabled, "This will cause a leak and performance issues, WorldDebugControls.DebuggingActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DebuggingActions
    private readonly InputActionMap m_DebuggingActions;
    private List<IDebuggingActionsActions> m_DebuggingActionsActionsCallbackInterfaces = new List<IDebuggingActionsActions>();
    private readonly InputAction m_DebuggingActions_HeightViewing;
    private readonly InputAction m_DebuggingActions_SlopeViewing;
    private readonly InputAction m_DebuggingActions_MoistureView;
    private readonly InputAction m_DebuggingActions_FlowView;
    private readonly InputAction m_DebuggingActions_BiomeView;
    private readonly InputAction m_DebuggingActions_Regenerate;
    /// <summary>
    /// Provides access to input actions defined in input action map "DebuggingActions".
    /// </summary>
    public struct DebuggingActionsActions
    {
        private @WorldDebugControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DebuggingActionsActions(@WorldDebugControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "DebuggingActions/HeightViewing".
        /// </summary>
        public InputAction @HeightViewing => m_Wrapper.m_DebuggingActions_HeightViewing;
        /// <summary>
        /// Provides access to the underlying input action "DebuggingActions/SlopeViewing".
        /// </summary>
        public InputAction @SlopeViewing => m_Wrapper.m_DebuggingActions_SlopeViewing;
        /// <summary>
        /// Provides access to the underlying input action "DebuggingActions/MoistureView".
        /// </summary>
        public InputAction @MoistureView => m_Wrapper.m_DebuggingActions_MoistureView;
        /// <summary>
        /// Provides access to the underlying input action "DebuggingActions/FlowView".
        /// </summary>
        public InputAction @FlowView => m_Wrapper.m_DebuggingActions_FlowView;
        /// <summary>
        /// Provides access to the underlying input action "DebuggingActions/BiomeView".
        /// </summary>
        public InputAction @BiomeView => m_Wrapper.m_DebuggingActions_BiomeView;
        /// <summary>
        /// Provides access to the underlying input action "DebuggingActions/Regenerate".
        /// </summary>
        public InputAction @Regenerate => m_Wrapper.m_DebuggingActions_Regenerate;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_DebuggingActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DebuggingActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DebuggingActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DebuggingActionsActions" />
        public void AddCallbacks(IDebuggingActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_DebuggingActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebuggingActionsActionsCallbackInterfaces.Add(instance);
            @HeightViewing.started += instance.OnHeightViewing;
            @HeightViewing.performed += instance.OnHeightViewing;
            @HeightViewing.canceled += instance.OnHeightViewing;
            @SlopeViewing.started += instance.OnSlopeViewing;
            @SlopeViewing.performed += instance.OnSlopeViewing;
            @SlopeViewing.canceled += instance.OnSlopeViewing;
            @MoistureView.started += instance.OnMoistureView;
            @MoistureView.performed += instance.OnMoistureView;
            @MoistureView.canceled += instance.OnMoistureView;
            @FlowView.started += instance.OnFlowView;
            @FlowView.performed += instance.OnFlowView;
            @FlowView.canceled += instance.OnFlowView;
            @BiomeView.started += instance.OnBiomeView;
            @BiomeView.performed += instance.OnBiomeView;
            @BiomeView.canceled += instance.OnBiomeView;
            @Regenerate.started += instance.OnRegenerate;
            @Regenerate.performed += instance.OnRegenerate;
            @Regenerate.canceled += instance.OnRegenerate;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DebuggingActionsActions" />
        private void UnregisterCallbacks(IDebuggingActionsActions instance)
        {
            @HeightViewing.started -= instance.OnHeightViewing;
            @HeightViewing.performed -= instance.OnHeightViewing;
            @HeightViewing.canceled -= instance.OnHeightViewing;
            @SlopeViewing.started -= instance.OnSlopeViewing;
            @SlopeViewing.performed -= instance.OnSlopeViewing;
            @SlopeViewing.canceled -= instance.OnSlopeViewing;
            @MoistureView.started -= instance.OnMoistureView;
            @MoistureView.performed -= instance.OnMoistureView;
            @MoistureView.canceled -= instance.OnMoistureView;
            @FlowView.started -= instance.OnFlowView;
            @FlowView.performed -= instance.OnFlowView;
            @FlowView.canceled -= instance.OnFlowView;
            @BiomeView.started -= instance.OnBiomeView;
            @BiomeView.performed -= instance.OnBiomeView;
            @BiomeView.canceled -= instance.OnBiomeView;
            @Regenerate.started -= instance.OnRegenerate;
            @Regenerate.performed -= instance.OnRegenerate;
            @Regenerate.canceled -= instance.OnRegenerate;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DebuggingActionsActions.UnregisterCallbacks(IDebuggingActionsActions)" />.
        /// </summary>
        /// <seealso cref="DebuggingActionsActions.UnregisterCallbacks(IDebuggingActionsActions)" />
        public void RemoveCallbacks(IDebuggingActionsActions instance)
        {
            if (m_Wrapper.m_DebuggingActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DebuggingActionsActions.AddCallbacks(IDebuggingActionsActions)" />
        /// <seealso cref="DebuggingActionsActions.RemoveCallbacks(IDebuggingActionsActions)" />
        /// <seealso cref="DebuggingActionsActions.UnregisterCallbacks(IDebuggingActionsActions)" />
        public void SetCallbacks(IDebuggingActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_DebuggingActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebuggingActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DebuggingActionsActions" /> instance referencing this action map.
    /// </summary>
    public DebuggingActionsActions @DebuggingActions => new DebuggingActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "DebuggingActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DebuggingActionsActions.AddCallbacks(IDebuggingActionsActions)" />
    /// <seealso cref="DebuggingActionsActions.RemoveCallbacks(IDebuggingActionsActions)" />
    public interface IDebuggingActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "HeightViewing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHeightViewing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SlopeViewing" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSlopeViewing(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoistureView" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoistureView(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FlowView" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFlowView(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BiomeView" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBiomeView(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Regenerate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRegenerate(InputAction.CallbackContext context);
    }
}
